name = ()
name.appent("vlad")
name.appent("misha")
name.appent("yarik")
name.appent("vlad2")
name.appent("denis")
name.appent("rinat")
name.appent("vanya")
name.appent("dana")
name.appent("nella")
name.appent("artem")
name.appent("roma")
print(name)
